name: Docker Build and Push

on:
  push:
    branches:
      - master  # Trigger this action when you push to the main branch
  # You can also add other triggers like pull_request if needed

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu environment

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/groupproject:${{ github.sha }} .

    # Step 4: Push the Docker image
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/groupproject:${{ github.sha }}
